
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
homeassistant:
  customize: !include customize.yaml

# MQTT Broker
mqtt:
  broker: 192.168.0.88
  discovery: true
  discovery_prefix: homeassistant

# Humidity sensors
sensor:
  - platform: mqtt
    name: "ESP32_Higrow_moisture"
    state_topic: "plant/sensor"
    value_template: '{{value_json.Moisture}}'
    unit_of_measurement: "%" 
    
  - platform: mqtt
    name: "ESP32_Higrow_temperature"
    state_topic: "plant/sensor"
    value_template: '{{value_json.Temperature}}'
    unit_of_measurement: "°C" 

  - platform: mqtt
    name: "ESP32_Higrow_humidity"
    state_topic: "plant/sensor"
    value_template: '{{value_json.Humidity}}'
    unit_of_measurement: "%" 

  - platform: template
    sensors:
      humidity:
        entity_id: sensor.esp32_higrow_moisture
        friendly_name: Plant Humidity
        value_template: >-
          {% if states('sensor.esp32_higrow_moisture')|float < 70 %}
            Dry
          {% else %}
            Wet
          {% endif %}

# Lovelace-floorplan example 
binary_sensor:
  - platform: mqtt
    name: Living Area
    state_topic: 'binary_sensor/living_area'
    
