esphome:
  name: esp32_pero
  platform: ESP32
  board: esp-wrover-kit

wifi:
  ssid: "Mamicu Odlazi"
  password: "inevracajse"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32 Pero Fallback Hotspot"
    password: "W0rXBtL8qx5T"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: "esphome"

ota:
  password: "esphome"
